version: '3'

services:
  spark-master:
    image: newspark
    command: bin/spark-class org.apache.spark.deploy.master.Master
    depends_on:
      - mongo
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./dataset:/data
      - ./APP:/opt/bitnami/spark/APP
      
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - spark-mongo-network

  spark-worker-1:
    image: newspark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081" 
    volumes:
      - ./dataset:/data
    networks:
      - spark-mongo-network

  spark-worker-2:
    image: newspark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8082:8081"  
    volumes:
      - ./dataset:/data
    networks:
      - spark-mongo-network

  spark-worker-3:
    image: newspark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8083:8081" 
    volumes:
      - ./dataset:/data
    networks:
      - spark-mongo-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: mongod --bind_ip_all
    networks:
      - spark-mongo-network


networks:
  spark-mongo-network:
    driver: bridge
